"""
Global web coverage taxonomy for BrowserMind real-world collection.

Counts are target task densities per layer (not exact unique domain counts).
"""

from __future__ import annotations

WEB_LAYERS = [
    {
        "id": "search_portals_navigation",
        "label": "Search, Portals, and Navigation Layer",
        "target_count": 20,
        "capabilities": ["search", "scroll", "extract"],
        "sites": [
            {"name": "Google", "url": "https://www.google.com"},
            {"name": "Bing", "url": "https://www.bing.com"},
            {"name": "Yahoo", "url": "https://www.yahoo.com"},
            {"name": "Yandex", "url": "https://yandex.com"},
            {"name": "Baidu", "url": "https://www.baidu.com"},
            {"name": "DuckDuckGo", "url": "https://duckduckgo.com"},
            {"name": "Brave Search", "url": "https://search.brave.com"},
            {"name": "Ecosia", "url": "https://www.ecosia.org"},
            {"name": "Startpage", "url": "https://www.startpage.com"},
            {"name": "Qwant", "url": "https://www.qwant.com"},
        ],
    },
    {
        "id": "social_attention",
        "label": "Social + Attention Platforms",
        "target_count": 60,
        "capabilities": ["search", "scroll", "like", "comment", "share", "post", "follow", "extract"],
        "sites": [
            {"name": "Facebook", "url": "https://www.facebook.com"},
            {"name": "Instagram", "url": "https://www.instagram.com"},
            {"name": "X", "url": "https://x.com/home"},
            {"name": "TikTok", "url": "https://www.tiktok.com"},
            {"name": "Reddit", "url": "https://www.reddit.com"},
            {"name": "LinkedIn", "url": "https://www.linkedin.com/feed"},
            {"name": "Snapchat Web", "url": "https://web.snapchat.com"},
            {"name": "Pinterest", "url": "https://www.pinterest.com"},
            {"name": "Threads", "url": "https://www.threads.net"},
            {"name": "Mastodon", "url": "https://mastodon.social/public"},
        ],
    },
    {
        "id": "video_streaming_media",
        "label": "Video, Streaming, Media",
        "target_count": 40,
        "capabilities": ["search", "scroll", "like", "comment", "share", "follow", "extract"],
        "sites": [
            {"name": "YouTube", "url": "https://www.youtube.com"},
            {"name": "Netflix", "url": "https://www.netflix.com"},
            {"name": "Twitch", "url": "https://www.twitch.tv"},
            {"name": "Disney Plus", "url": "https://www.disneyplus.com"},
            {"name": "Vimeo", "url": "https://vimeo.com"},
            {"name": "Prime Video", "url": "https://www.primevideo.com"},
            {"name": "Dailymotion", "url": "https://www.dailymotion.com"},
            {"name": "Hulu", "url": "https://www.hulu.com"},
        ],
    },
    {
        "id": "ecommerce_marketplaces",
        "label": "E-commerce and Marketplaces",
        "target_count": 70,
        "capabilities": ["search", "scroll", "extract", "follow"],
        "sites": [
            {"name": "Amazon", "url": "https://www.amazon.com"},
            {"name": "eBay", "url": "https://www.ebay.com"},
            {"name": "AliExpress", "url": "https://www.aliexpress.com"},
            {"name": "Alibaba", "url": "https://www.alibaba.com"},
            {"name": "Walmart", "url": "https://www.walmart.com"},
            {"name": "Etsy", "url": "https://www.etsy.com"},
            {"name": "Target", "url": "https://www.target.com"},
            {"name": "Best Buy", "url": "https://www.bestbuy.com"},
            {"name": "Newegg", "url": "https://www.newegg.com"},
            {"name": "Shopify", "url": "https://www.shopify.com"},
        ],
    },
    {
        "id": "knowledge_docs_reference",
        "label": "Knowledge, Docs, and Reference",
        "target_count": 40,
        "capabilities": ["search", "scroll", "extract", "comment"],
        "sites": [
            {"name": "Wikipedia", "url": "https://www.wikipedia.org"},
            {"name": "Google Docs", "url": "https://docs.google.com"},
            {"name": "Notion", "url": "https://www.notion.so"},
            {"name": "Quora", "url": "https://www.quora.com"},
            {"name": "Stack Overflow", "url": "https://stackoverflow.com"},
            {"name": "Khan Academy", "url": "https://www.khanacademy.org"},
            {"name": "Britannica", "url": "https://www.britannica.com"},
            {"name": "Wolfram", "url": "https://www.wolframalpha.com"},
        ],
    },
    {
        "id": "news_publishing",
        "label": "News and Publishing",
        "target_count": 50,
        "capabilities": ["search", "scroll", "extract", "share", "follow"],
        "sites": [
            {"name": "BBC", "url": "https://www.bbc.com/news"},
            {"name": "CNN", "url": "https://www.cnn.com"},
            {"name": "New York Times", "url": "https://www.nytimes.com"},
            {"name": "The Guardian", "url": "https://www.theguardian.com"},
            {"name": "Al Jazeera", "url": "https://www.aljazeera.com"},
            {"name": "Reuters", "url": "https://www.reuters.com"},
            {"name": "Associated Press", "url": "https://apnews.com"},
            {"name": "WSJ", "url": "https://www.wsj.com"},
            {"name": "Bloomberg", "url": "https://www.bloomberg.com"},
            {"name": "TechCrunch", "url": "https://techcrunch.com"},
        ],
    },
    {
        "id": "saas_productivity_cloud",
        "label": "SaaS, Productivity, Cloud",
        "target_count": 60,
        "capabilities": ["search", "scroll", "extract", "comment", "share", "post", "follow"],
        "sites": [
            {"name": "Google Drive", "url": "https://drive.google.com"},
            {"name": "Dropbox", "url": "https://www.dropbox.com"},
            {"name": "Slack", "url": "https://slack.com"},
            {"name": "Zoom", "url": "https://zoom.us"},
            {"name": "Microsoft 365", "url": "https://www.microsoft365.com"},
            {"name": "Airtable", "url": "https://airtable.com"},
            {"name": "Asana", "url": "https://asana.com"},
            {"name": "Trello", "url": "https://trello.com"},
            {"name": "Monday", "url": "https://monday.com"},
            {"name": "ClickUp", "url": "https://clickup.com"},
        ],
    },
    {
        "id": "developer_technical",
        "label": "Developer and Technical Ecosystem",
        "target_count": 30,
        "capabilities": ["search", "scroll", "extract", "comment", "share", "follow"],
        "sites": [
            {"name": "GitHub", "url": "https://github.com"},
            {"name": "GitLab", "url": "https://gitlab.com"},
            {"name": "Stack Overflow", "url": "https://stackoverflow.com"},
            {"name": "Hugging Face", "url": "https://huggingface.co"},
            {"name": "PyPI", "url": "https://pypi.org"},
            {"name": "NPM", "url": "https://www.npmjs.com"},
            {"name": "Docker Hub", "url": "https://hub.docker.com"},
            {"name": "Kaggle", "url": "https://www.kaggle.com"},
        ],
    },
    {
        "id": "finance_crypto_payments",
        "label": "Finance, Crypto, Payments",
        "target_count": 30,
        "capabilities": ["search", "scroll", "extract", "follow"],
        "sites": [
            {"name": "PayPal", "url": "https://www.paypal.com"},
            {"name": "Stripe", "url": "https://stripe.com"},
            {"name": "Binance", "url": "https://www.binance.com"},
            {"name": "Coinbase", "url": "https://www.coinbase.com"},
            {"name": "Kraken", "url": "https://www.kraken.com"},
            {"name": "TradingView", "url": "https://www.tradingview.com"},
            {"name": "Yahoo Finance", "url": "https://finance.yahoo.com"},
            {"name": "Investing", "url": "https://www.investing.com"},
        ],
    },
    {
        "id": "travel_maps_local",
        "label": "Travel, Maps, Local",
        "target_count": 30,
        "capabilities": ["search", "scroll", "extract", "follow"],
        "sites": [
            {"name": "Google Maps", "url": "https://maps.google.com"},
            {"name": "Booking", "url": "https://www.booking.com"},
            {"name": "Airbnb", "url": "https://www.airbnb.com"},
            {"name": "Uber", "url": "https://www.uber.com"},
            {"name": "Tripadvisor", "url": "https://www.tripadvisor.com"},
            {"name": "Expedia", "url": "https://www.expedia.com"},
            {"name": "Skyscanner", "url": "https://www.skyscanner.com"},
            {"name": "Kayak", "url": "https://www.kayak.com"},
        ],
    },
    {
        "id": "high_traffic_misc",
        "label": "File Sharing and Misc High Traffic",
        "target_count": 40,
        "capabilities": ["search", "scroll", "extract"],
        "sensitive": True,
        "sites": [
            {"name": "Mega", "url": "https://mega.io"},
            {"name": "MediaFire", "url": "https://www.mediafire.com"},
            {"name": "WeTransfer", "url": "https://wetransfer.com"},
            {"name": "4shared", "url": "https://www.4shared.com"},
            {"name": "Pastebin", "url": "https://pastebin.com"},
            {"name": "Archive", "url": "https://archive.org"},
            {"name": "SourceForge", "url": "https://sourceforge.net"},
            {"name": "Fandom", "url": "https://www.fandom.com"},
        ],
    },
]
