"""One-shot helper: writes BrowserMind.bat with CRLF line endings."""
from pathlib import Path

S = chr(47)   # /
PCT = chr(37) # %
TILDE = chr(126)  # ~

CD = f"cd {S}d \"{PCT}{TILDE}dp0\""

LINES = [
    "@echo off",
    CD,
    "",
    ":MAIN_MENU",
    "cls",
    "echo ====================================================================",
    "echo   BrowserMind  -  Control Center",
    "echo ====================================================================",
    "echo.",
    "echo   SYSTEM STATUS:",
    "echo.",
    "python bm.py status 2>nul ^|^| echo   (status unavailable - is venv active?)",
    "echo.",
    "echo ====================================================================",
    "echo.",
    "echo   -- Core --------------------------------------------------------",
    "echo    [1]  System Status and Health",
    "echo    [2]  Record a workflow",
    "echo    [3]  Train and Learn",
    "echo    [4]  Explore and Discover",
    "echo    [5]  Replay a workflow",
    "echo    [6]  Run benchmark suite",
    "echo.",
    "echo   -- Discovery ---------------------------------------------------",
    "echo    [7]  Discovery Validation (fallback-rate measurement)",
    "echo    [8]  Anti-Bot Tools",
    "echo.",
    "echo   -- Control -----------------------------------------------------",
    "echo    [9]  Mission Control / Live Watch",
    "echo   [10]  Pause running engine",
    "echo   [11]  Resume engine",
    "echo.",
    "echo   -- Dev ---------------------------------------------------------",
    "echo   [12]  Run all tests",
    "echo   [13]  View hypothesis store stats",
    "echo.",
    "echo    [0]  Exit",
    "echo.",
    'set /p CHOICE=  Choice: ',
    "",
    'if "%CHOICE%"=="1"  goto STATUS',
    'if "%CHOICE%"=="2"  goto RECORD_MENU',
    'if "%CHOICE%"=="3"  goto TRAIN_MENU',
    'if "%CHOICE%"=="4"  goto EXPLORE_MENU',
    'if "%CHOICE%"=="5"  goto REPLAY_MENU',
    'if "%CHOICE%"=="6"  goto BENCHMARK',
    'if "%CHOICE%"=="7"  goto DISCOVERY_VALIDATION',
    'if "%CHOICE%"=="8"  goto ANTIBOT_TOOLS',
    'if "%CHOICE%"=="9"  goto MISSION_CONTROL',
    'if "%CHOICE%"=="10" goto PAUSE_ENGINE',
    'if "%CHOICE%"=="11" goto RESUME_ENGINE',
    'if "%CHOICE%"=="12" goto RUN_TESTS',
    'if "%CHOICE%"=="13" goto HYPOTHESIS_STATS',
    'if "%CHOICE%"=="0"  exit /b 0',
    "goto MAIN_MENU",
    "",
    ":STATUS",
    "cls",
    "echo === System Status ===",
    "echo.",
    "python bm.py status",
    "echo.",
    "echo --- Python environment ---",
    "python --version",
    'pip list 2>nul ^| findstr /i "playwright torch transformers"',
    "echo.",
    "pause",
    "goto MAIN_MENU",
    "",
    ":RECORD_MENU",
    "cls",
    "echo === Record a Workflow ===",
    "echo.",
    "echo   [1]  SauceDemo  [2]  DemoQA  [3]  the-internet  [4]  Greenhouse  [5]  Back",
    "echo.",
    'set /p RSITE=  Site: ',
    'if "%RSITE%"=="1" call "%~dp0scripts\\recording\\RECORD_saucedemo.bat"',
    'if "%RSITE%"=="2" call "%~dp0scripts\\recording\\RECORD_demoqa.bat"',
    'if "%RSITE%"=="3" call "%~dp0scripts\\recording\\RECORD_the_internet.bat"',
    'if "%RSITE%"=="4" call "%~dp0scripts\\recording\\RECORD_greenhouse.bat"',
    "goto MAIN_MENU",
    "",
    ":TRAIN_MENU",
    "cls",
    "echo === Train and Learn ===",
    "echo.",
    "echo   [1]  PHASE3 training  [2]  Self-train  [3]  Scheduler  [4]  Back",
    "echo.",
    'set /p TCHOICE=  Choice: ',
    'if "%TCHOICE%"=="1" call "%~dp0scripts\\PHASE3_train.bat"',
    'if "%TCHOICE%"=="2" ( python bm.py self-train --headless & pause )',
    'if "%TCHOICE%"=="3" call "%~dp0scripts\\SELF_TRAIN_setup_scheduler.bat"',
    "goto MAIN_MENU",
    "",
    ":EXPLORE_MENU",
    "cls",
    "echo === Explore and Discover ===",
    "echo.",
    "echo   Discovers capability hypotheses by browsing a site autonomously.",
    "echo   Fallbacks are recorded in FallbackLedger for vocab induction.",
    "echo.",
    'set /p ESITE=  Site key (e.g. saucedemo, demoqa, aria_internet, github): ',
    'set /p EBUDGET=  Budget steps (default 50): ',
    'set /p EHEADLESS=  Headless? (y/N): ',
    'if "%EBUDGET%"=="" set EBUDGET=50',
    'set EHEADLESS_FLAG=',
    'if /i "%EHEADLESS%"=="y" set EHEADLESS_FLAG=--headless',
    "echo.",
    "echo   Launching ... (output below)",
    "echo.",
    "python bm.py explore --site %ESITE% --budget %EBUDGET% %EHEADLESS_FLAG%",
    "pause",
    "goto MAIN_MENU",
    "",
    ":REPLAY_MENU",
    "cls",
    "echo === Replay a Workflow ===",
    "echo.",
    "python bm.py workflow template ls 2>nul",
    "echo.",
    'set /p TMPL=  Template name: ',
    'set /p RENV=  Environment key: ',
    'set /p RPERSONA=  Persona name: ',
    'set /p RSKIP=  Skip failures? (y/N): ',
    'if /i "%RSKIP%"=="y" ( python bm.py replay start %TMPL% --env %RENV% --persona %RPERSONA% --skip-failures ) else ( python bm.py replay start %TMPL% --env %RENV% --persona %RPERSONA% )',
    "pause",
    "goto MAIN_MENU",
    "",
    ":BENCHMARK",
    "cls",
    "echo === Benchmark Suite ===",
    "echo.",
    'set /p BRUNS=  Number of runs (default 3): ',
    'if "%BRUNS%"=="" set BRUNS=3',
    "python bm.py benchmark run --headless --runs %BRUNS%",
    "pause",
    "goto MAIN_MENU",
    "",
    ":DISCOVERY_VALIDATION",
    "cls",
    "echo === Discovery Validation ===",
    "echo.",
    "python scripts\\bm_validate.py",
    "pause",
    "goto MAIN_MENU",
    "",
    ":ANTIBOT_TOOLS",
    "cls",
    "echo === Anti-Bot Tools ===",
    "echo.",
    "echo   [1]  Site tiers  [2]  bot_detected summary  [3]  Back",
    "echo.",
    'set /p ABCHOICE=  Choice: ',
    'if "%ABCHOICE%"=="1" ( echo. & python scripts\\bm_antibot.py & echo. & pause )',
    'if "%ABCHOICE%"=="2" ( echo. & echo   see training\\failure_buffer\\harvested\\bot_detected.jsonl & echo. & pause )',
    'if "%ABCHOICE%"=="3" goto MAIN_MENU',
    "goto MAIN_MENU",
    "",
    ":MISSION_CONTROL",
    "cls",
    "echo === Mission Control - Live Watch ===",
    "echo.",
    "echo   Controls: p=pause  r=resume  q=quit",
    "echo.",
    "python scripts\\live_watch.py",
    "goto MAIN_MENU",
    "",
    ":PAUSE_ENGINE",
    "cls",
    "echo === Pausing Engine ===",
    "echo.",
    'if not exist "%USERPROFILE%\\.browsermind" mkdir "%USERPROFILE%\\.browsermind"',
    'echo paused > "%USERPROFILE%\\.browsermind\\_pause_requested"',
    "echo   Sentinel written - engine pauses at next step. Use [11] to resume.",
    "echo.",
    "pause",
    "goto MAIN_MENU",
    "",
    ":RESUME_ENGINE",
    "cls",
    "echo === Resuming Engine ===",
    "echo.",
    'if exist "%USERPROFILE%\\.browsermind\\_pause_requested" ( del "%USERPROFILE%\\.browsermind\\_pause_requested" & echo   Sentinel deleted. ) else ( echo   Engine was not paused. )',
    "echo.",
    "pause",
    "goto MAIN_MENU",
    "",
    ":RUN_TESTS",
    "cls",
    "echo === Running All Tests ===",
    "echo.",
    "python -m pytest browsermind_core\\tests\\ -v --tb=short -q",
    "echo.",
    "pause",
    "goto MAIN_MENU",
    "",
    ":HYPOTHESIS_STATS",
    "cls",
    "echo === Hypothesis Store Stats ===",
    "echo.",
    "python scripts\\bm_stats.py",
    "pause",
    "goto MAIN_MENU",
]

out = Path(__file__).parent.parent / "BrowserMind.bat"
content = "\r\n".join(LINES) + "\r\n"
out.write_bytes(content.encode("ascii"))

data = out.read_bytes()
crlf = data.count(b"\r\n")
lf_only = data.count(b"\n") - crlf
print(f"Written: {out}")
print(f"  {len(data)} bytes | CRLF={crlf} | LF-only={lf_only} (should be 0)")
